if respond_to?(:require)

  framework 'CoreMIDI'

  require File.expand_path('../../motion/midi/exception.rb', __FILE__)
  require File.expand_path('../../motion/midi/midi_object_cache.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/unique_id.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/advance_schedule_time.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/can_route.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/connection_unique_id.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/device_id.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/display_name.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/driver_device_editor_app.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/driver_owner.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/driver_version.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/image.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/is_drum_machine.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/is_effect_unit.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/is_mixer.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/is_sampler.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/is_broadcast.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/is_embedded_entity.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/manufacturer.rb', __FILE__)
  require File.expand_path('../../motion/midi/ext/max_receive_channels.rb', __FILE__)
  require File.expand_path('../../motion/midi/midi_object.rb', __FILE__)
  require File.expand_path('../../motion/midi/device.rb', __FILE__)
  require File.expand_path('../../motion/midi/entity.rb', __FILE__)
  require File.expand_path('../../motion/midi/source.rb', __FILE__)
  require File.expand_path('../../motion/midi/client.rb', __FILE__)
  require File.expand_path('../../motion/midi/destination.rb', __FILE__)
  require File.expand_path('../../motion/midi/port.rb', __FILE__)
  require File.expand_path('../../motion/midi/input_port.rb', __FILE__)
  require File.expand_path('../../motion/midi/output_port.rb', __FILE__)
  require File.expand_path('../../motion/midi.rb', __FILE__)

end

BW = BubbleWrap unless defined?(BW)
